services:
  - type: web
    name: dzero-backend
    env: node
    buildCommand: |
      cd src
      make
    startCommand: |
      node backend/server.js
    envVars:
      - key: ENGINE_PATH
        value: src/chess
